services:
  privoxy:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        expose: 8118
    image: adblock_privoxy
    ports:
      - "8118:8118"
    volumes:
      - ./scripts:/scripts
      - ./hosts:/hosts
      - ./privoxy/user.action:/config/privoxy/user.action:ro
      - ./privoxy/user.filter:/config/privoxy/user.filter:ro
      - ./privoxy/blocklist.conf:/etc/privoxy/blocklist.conf:ro
    restart: always
    tty: true
    command: /bin/bash
    entrypoint: >
      /bin/bash -c "cp -f /config/privoxy/* /etc/privoxy/;\
                    /scripts/01downloader.sh;\
                    /scripts/02update_user_action.sh;\
                    /scripts/99setup.sh;\
                    privoxy --no-daemon /etc/privoxy/config"
